#include "hal/hal_ledc_gen.h"
#include <Arduino.h>
#include <math.h>
#include "driver/ledc.h"
#include "esp_timer.h"
#include "esp_log.h"
#include "driver/gpio.h"

static const char *TAG = "HAL_LEDC_GEN";

#define LEDC_TIMER_NUM          LEDC_TIMER_0
#define LEDC_MODE_DEFAULT       LEDC_HIGH_SPEED_MODE
#define LEDC_CHANNEL_NUM        LEDC_CHANNEL_0

static ledc_gen_status_t s_status = {
    .frequency_hz = 10000,
    .duty_cycle_pct = 50,
    .output_gpio = 19,
    .enabled = false,
    .res_bits = 10,
    .div_param = 2000,
    .calc_freq_hz = 10000.0
};

static bool s_is_inited = false;
static esp_timer_handle_t s_low_freq_timer = NULL;
static volatile int s_low_freq_pin_level = 0;
static bool s_is_low_freq_mode = false;

static void low_freq_timer_cb(void *arg) {
    s_low_freq_pin_level = !s_low_freq_pin_level;
    gpio_set_level((gpio_num_t)s_status.output_gpio, s_low_freq_pin_level);
}

// Find optimal resolution between 4 and 14 bits for ESP32 LEDC hardware
static ledc_timer_bit_t find_best_resolution(uint32_t freq_hz, uint32_t *out_div_param) {
    for (int res = 14; res >= 4; res--) {
        uint64_t denom = (uint64_t)freq_hz * (1ULL << res);
        uint64_t div_param = ((uint64_t)80000000ULL * 256ULL) / denom;
        if (div_param >= 256 && div_param < 262144) {
            if (out_div_param) *out_div_param = (uint32_t)div_param;
            return (ledc_timer_bit_t)res;
        }
    }
    if (out_div_param) *out_div_param = 256;
    return LEDC_TIMER_4_BIT;
}

esp_err_t hal_ledc_gen_init(int gpio_num) {
    if (s_is_inited) {
        hal_ledc_gen_deinit();
    }
    s_status.output_gpio = gpio_num;

    gpio_config_t io_conf = {
        .pin_bit_mask = (1ULL << gpio_num),
        .mode = GPIO_MODE_OUTPUT,
        .pull_up_en = GPIO_PULLUP_DISABLE,
        .pull_down_en = GPIO_PULLDOWN_DISABLE,
        .intr_type = GPIO_INTR_DISABLE
    };
    gpio_config(&io_conf);
    gpio_set_level((gpio_num_t)gpio_num, 0);

    const esp_timer_create_args_t timer_args = {
        .callback = &low_freq_timer_cb,
        .name = "low_freq_gen_timer"
    };
    esp_timer_create(&timer_args, &s_low_freq_timer);

    s_is_inited = true;
    s_status.enabled = false;
    return hal_ledc_gen_set_frequency(s_status.frequency_hz, s_status.duty_cycle_pct);
}

esp_err_t hal_ledc_gen_set_frequency(uint32_t freq_hz, uint8_t duty_pct) {
    if (!s_is_inited) return ESP_ERR_INVALID_STATE;
    if (freq_hz == 0) return ESP_ERR_INVALID_ARG;
    if (duty_pct > 100) duty_pct = 100;

    // Frequencies above 5 MHz cannot be generated by LEDC on ESP32 (requires div >= 1.0 with >= 4-bit res)
    if (freq_hz > 5000000) {
        ESP_LOGW(TAG, "Frequency %lu Hz exceeds ESP32 LEDC 4-bit limit (5.0 MHz)", (unsigned long)freq_hz);
        return ESP_ERR_NOT_SUPPORTED;
    }

    // Below 50 Hz: 64-bit microsecond hardware timer toggle (exact square wave)
    if (freq_hz < 50) {
        if (!s_is_low_freq_mode) {
            ledc_stop(LEDC_MODE_DEFAULT, LEDC_CHANNEL_NUM, 0);
            gpio_set_direction((gpio_num_t)s_status.output_gpio, GPIO_MODE_OUTPUT);
            s_is_low_freq_mode = true;
        }

        s_status.frequency_hz = freq_hz;
        s_status.duty_cycle_pct = 50;
        s_status.res_bits = 0;
        s_status.div_param = 0;
        s_status.calc_freq_hz = (double)freq_hz;

        if (s_status.enabled) {
            esp_timer_stop(s_low_freq_timer);
            uint64_t half_period_us = (1000000ULL / freq_hz) / 2;
            if (half_period_us == 0) half_period_us = 1;
            esp_timer_start_periodic(s_low_freq_timer, half_period_us);
        }
        ESP_LOGI(TAG, "Configured Timer: %lu Hz (Half-period: %llu us)", (unsigned long)freq_hz, (1000000ULL / freq_hz) / 2);
        return ESP_OK;
    }

    // 50 Hz to 5 MHz: LEDC hardware generator
    if (s_is_low_freq_mode) {
        esp_timer_stop(s_low_freq_timer);
        s_is_low_freq_mode = false;
    }

    uint32_t div_param = 0;
    ledc_timer_bit_t res = find_best_resolution(freq_hz, &div_param);

    ledc_timer_config_t ledc_timer = {
        .speed_mode       = LEDC_MODE_DEFAULT,
        .duty_resolution  = res,
        .timer_num        = LEDC_TIMER_NUM,
        .freq_hz          = freq_hz,
        .clk_cfg          = LEDC_USE_APB_CLK
    };
    esp_err_t err = ledc_timer_config(&ledc_timer);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_timer_config failed for %lu Hz: %s", (unsigned long)freq_hz, esp_err_to_name(err));
        return err;
    }

    uint32_t max_duty = (1 << res);
    uint32_t duty = (max_duty * duty_pct) / 100;
    if (duty >= max_duty) duty = max_duty - 1;

    ledc_channel_config_t ledc_channel = {
        .gpio_num       = s_status.output_gpio,
        .speed_mode     = LEDC_MODE_DEFAULT,
        .channel        = LEDC_CHANNEL_NUM,
        .intr_type      = LEDC_INTR_DISABLE,
        .timer_sel      = LEDC_TIMER_NUM,
        .duty           = s_status.enabled ? duty : 0,
        .hpoint         = 0
    };
    err = ledc_channel_config(&ledc_channel);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "ledc_channel_config failed: %s", esp_err_to_name(err));
        return err;
    }

    if (s_status.enabled) {
        ledc_set_duty(LEDC_MODE_DEFAULT, LEDC_CHANNEL_NUM, duty);
        ledc_update_duty(LEDC_MODE_DEFAULT, LEDC_CHANNEL_NUM);
    }

    s_status.frequency_hz = freq_hz;
    s_status.duty_cycle_pct = duty_pct;
    s_status.res_bits = (uint8_t)res;
    s_status.div_param = div_param;
    s_status.calc_freq_hz = ((80000000.0 * 256.0) / ((double)div_param * (1 << res)));

    ESP_LOGI(TAG, "Configured LEDC: req=%lu Hz, res=%d bit, div_param=%lu (div=%.3f), calc_f=%.2f Hz",
             (unsigned long)freq_hz, (int)res, (unsigned long)div_param, div_param / 256.0, s_status.calc_freq_hz);

    return ESP_OK;
}

esp_err_t hal_ledc_gen_start(void) {
    if (!s_is_inited) return ESP_ERR_INVALID_STATE;
    s_status.enabled = true;
    return hal_ledc_gen_set_frequency(s_status.frequency_hz, s_status.duty_cycle_pct);
}

esp_err_t hal_ledc_gen_stop(void) {
    if (!s_is_inited) return ESP_ERR_INVALID_STATE;

    if (s_is_low_freq_mode && s_low_freq_timer) {
        esp_timer_stop(s_low_freq_timer);
        gpio_set_level((gpio_num_t)s_status.output_gpio, 0);
    } else {
        ledc_stop(LEDC_MODE_DEFAULT, LEDC_CHANNEL_NUM, 0);
    }
    s_status.enabled = false;
    ESP_LOGI(TAG, "Reference generator stopped");
    return ESP_OK;
}

esp_err_t hal_ledc_gen_deinit(void) {
    hal_ledc_gen_stop();
    if (s_low_freq_timer) {
        esp_timer_delete(s_low_freq_timer);
        s_low_freq_timer = NULL;
    }
    s_is_inited = false;
    return ESP_OK;
}

ledc_gen_status_t hal_ledc_gen_get_status(void) {
    return s_status;
}

// Multi-channel test pattern generator (4 concurrent independent frequencies)
static const int QUAD_PINS[4] = {19, 21, 22, 23};
static const ledc_timer_t QUAD_TIMERS[4] = {LEDC_TIMER_0, LEDC_TIMER_1, LEDC_TIMER_2, LEDC_TIMER_3};
static const ledc_channel_t QUAD_CHANS[4] = {LEDC_CHANNEL_0, LEDC_CHANNEL_1, LEDC_CHANNEL_2, LEDC_CHANNEL_3};

esp_err_t hal_ledc_gen_start_quad(uint32_t f0, uint32_t f1, uint32_t f2, uint32_t f3) {
    uint32_t freqs[4] = {f0, f1, f2, f3};

    for (int i = 0; i < 4; i++) {
        if (freqs[i] == 0) continue;
        uint32_t div = 0;
        ledc_timer_bit_t res = find_best_resolution(freqs[i], &div);

        ledc_timer_config_t timer_cfg = {
            .speed_mode = LEDC_MODE_DEFAULT,
            .duty_resolution = res,
            .timer_num = QUAD_TIMERS[i],
            .freq_hz = freqs[i],
            .clk_cfg = LEDC_USE_APB_CLK
        };
        ledc_timer_config(&timer_cfg);

        uint32_t duty = (1 << res) / 2; // 50% duty
        ledc_channel_config_t ch_cfg = {
            .gpio_num = QUAD_PINS[i],
            .speed_mode = LEDC_MODE_DEFAULT,
            .channel = QUAD_CHANS[i],
            .intr_type = LEDC_INTR_DISABLE,
            .timer_sel = QUAD_TIMERS[i],
            .duty = duty,
            .hpoint = 0
        };
        ledc_channel_config(&ch_cfg);
        ledc_set_duty(LEDC_MODE_DEFAULT, QUAD_CHANS[i], duty);
        ledc_update_duty(LEDC_MODE_DEFAULT, QUAD_CHANS[i]);

        ESP_LOGI(TAG, "Quad Gen CH%d on GPIO %d: %lu Hz (Res %d-bit)", i, QUAD_PINS[i], (unsigned long)freqs[i], (int)res);
    }
    return ESP_OK;
}

esp_err_t hal_ledc_gen_stop_quad(void) {
    for (int i = 0; i < 4; i++) {
        ledc_stop(LEDC_MODE_DEFAULT, QUAD_CHANS[i], 0);
        gpio_set_direction((gpio_num_t)QUAD_PINS[i], GPIO_MODE_INPUT);
    }
    ESP_LOGI(TAG, "Quad generator stopped");
    return ESP_OK;
}

